### ISSUE TITLE
Many predicates don't conform to the standard forms

### ISSUE THREAD

**Issue by goodmami** [delph-in/jacy#2]
In light of [recent conversations](http://lists.delph-in.net/archives/developers/2015/002154.html) and [wikis](http://moin.delph-in.net/PredicateRfc), I'm updating this bug to be more inclusive about other kinds of non-conforming predicates.

There are problems introduced by automatic lexical entry creation (see #22), and ones that just haven't been brought up to speed with current conventions (e.g. the `"coord"` predicate originally the focus of this issue). Others seem to have an additional field (e.g. the `g` in `"_くもる_v_1_g_rel"`).

What would it take to fix this? Several grammar files need to be updated (particularly the lexicon, but also `core.smi`, trigger rules, MT rules, the type hierarchy for type preds). Do the profiles need to be reparsed, as well, or can that wait?

The original issue text is below:

> It was decided at some recent DELPH-IN summit that all predicates should end in "_rel".
> Jacy is creating "coord" as a predicate in at least these places:
> 
> trigger.mtr: lines 75 and 79
> japgram.tdl: line 642
> 
> Running a grep pattern like this might uncover some others, though I'm not sure about them:
> 
> `$ grep 'PRED "[^"]*[^r][^e][^l]"' *`

**Comment by goodmami** [comment]
And it looks like the `_g_rel` predicates are the automatically **g**enerated entries in [`lex/tanaka-unknowns.tdl`](../tree/master/lex/tanaka-unknowns.tdl). E.g. `"_あっと言う間に_r_1_g_rel"`. If these are unknowns, we could follow the normal pattern for unknown preds `"_あっと言う間に/RB_u_unknown_rel"`, but that gets rid of the `r` POS value (although there's `RB` embedded in the lemma field). Alternatively, if the fact that they are auto-generated needs to be noted somewhere, we can combine it with the sense without using an underscore: `"_あっと言う間に_r_1-g_rel"`

**Comment by fcbond** [comment]
Thanks.  We have put off updating these due to the need to update profiles simultaneously, but I hope to get Taka to look at these soon.

**Comment by goodmami** [comment]
Found some more:

Surface predicates that have more than one character in the POS field (e.g. they have the (optional) sense field but not the (required) POS field):

```
goodmami@tpy:~/grammars/jacy$ grep -n 'PRED "_[^_]*_[^_ ][^_ ]' lexicon.tdl 
21524:   SYNSEM.LKEYS.KEYREL.PRED "_nakademo_conj_rel",
21529:   SYNSEM.LKEYS.KEYREL.PRED "_nakademo_conj_rel",
21534:   SYNSEM [ LKEYS.KEYREL.PRED "_no_nmod_rel",
21544:   SYNSEM.LKEYS.KEYREL.PRED "_sunawachi_conj_rel",
21549:   SYNSEM.LKEYS.KEYREL.PRED "_sunawachi_conj_rel",
21558:   SYNSEM.LKEYS.KEYREL.PRED "_tokuni_conj_rel",
21600:   SYNSEM.LKEYS.KEYREL.PRED "_comma_conj_rel",
24544:   SYNSEM.LKEYS.KEYREL.PRED "_kara_nmod_rel",
24549:   SYNSEM [ LKEYS.KEYREL.PRED "_dash_nmod_rel",
24988:   SYNSEM.LKEYS.KEYREL.PRED "_te_adjunct_rel",
28478:   SYNSEM.LKEYS.KEYREL.PRED "_dot_conj_rel",
41399:   SYNSEM.LKEYS.KEYREL.PRED "_gashun_idiom_1_rel",
77780:   SYNSEM.LKEYS.KEYREL.PRED "_jooku_n1_rel",
205475:   SYNSEM.LKEYS.KEYREL.PRED "_sou_12_rel",
217895:   SYNSEM.LKEYS.KEYREL.PRED "_te_adjunct_rel",
217900:   SYNSEM.LKEYS.KEYREL.PRED "_ni_adjunct_rel",
```

Surface predicates that don't end in `_rel` (I think this is required in the lexicon as a namespace for symbols):

```
goodmami@tpy:~/grammars/jacy$ grep -n 'PRED "_[^"]*"' lexicon.tdl | grep -v '_rel"'
29682:   SYNSEM.LKEYS.KEYREL.PRED "_e-mail_n_1rel",
161934:   SYNSEM.LKEYS.KEYREL.PRED "_omoshiro_a_3rel",
174465:   SYNSEM.LKEYS.KEYREL.PRED "_ritorun_a_1rel",
231390:   SYNSEM [ LKEYS.KEYREL.PRED "_tteiunowa",
```
