### ISSUE TITLE
Replace preds with native-orthography equivalents

### ISSUE THREAD

**Issue by goodmami** [delph-in/jacy#22]
**EDIT**: Based on fcbond's comment, I'm changing this bug to "replace preds with native-orthography equivalents". We need some guidelines on how to do this (when to use hiragana/katakana/kanji for the lemma? should we use Japanese orthography for the sense as well? etc...).

_Original text below_:

I see many predicates in the lexicon that appear to have been over-aggressively modified (global search+replace, maybe), yielding strange forms. It seems to affect those with long vowels. E.g.:

```
yuniho-mu_1 := ordinary-nohon-n-lex &
  [ STEM < "ユニホーム" >,
    SYNSEM.LKEYS.KEYREL.PRED "_yuniho_n_mu_1_rel",
    TRAITS native_token_list ].
```

Shouldn't this be `"_yuniho-mu_n_1_rel"`?

Similarly:

| orth | pred |
| --- | --- |
| アート | `_a_n_to_1_rel` |
| アットホーム | `"_attoho_a_mu_1_rel"` |
| ベージュ | "_be_n_ju_1_rel" |

And many more. I found them with a regex like this: `/_[^_ ]\+_[^_ ]\+_[^_ ]\+_[^_ ]\+_rel/`

**Comment by fcbond** [comment]
known, annoying bug.  The solution is to replace by Kanji/hiragana, ...

On Mon, Aug 10, 2015 at 1:49 PM, Michael Wayne Goodman <
notifications@github.com> wrote:

> I see many predicates in the lexicon that appear to have been
> over-aggressively modified (global search+replace, maybe), yielding strange
> forms. It seems to affect those with long vowels. E.g.:
>
> yuniho-mu_1 := ordinary-nohon-n-lex &
>   [ STEM < "ユニホーム" >,
>     SYNSEM.LKEYS.KEYREL.PRED "_yuniho_n_mu_1_rel",
>     TRAITS native_token_list ].
>
> Shouldn't this be "_yuniho-mu_n_1_rel"?
>
> Similarly:
> orth pred アート _a_n_to_1_rel アットホーム "_attoho_a_mu_1_rel" ベージュ
> "_be_n_ju_1_rel"
>
> And many more. I found them with a regex like this: /_[^_ ]\+_[^_ ]\+_[^_
> ]\+_[^_ ]\+_rel/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/delph-in/jacy/issues/22>.
>



-- 
Francis Bond <http://www3.ntu.edu.sg/home/fcbond/>
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by goodmami** [comment]
Can we fix this one along with the new SEM-I (see issue #32 and PR #44)? Otherwise we'll have to redo much of the surface.smi file again.

**Comment by goodmami** [comment]
Commit 0d1539887d13dcc72577cb1d5cfb27ff4070cf35 resolved the problematic preds described by this issue, so I think the issue can be closed. Converting the rest of the predicates to the native orthography versions is rife with other complexities, so we'll leave that for another issue.
