### ISSUE TITLE
Generate newer SEM-I (1.0 version)

### ISSUE THREAD

**Issue by goodmami** [delph-in/jacy#32]
The ERG (at least in the LOGON tree; not trunk) has the newer SEM-I which includes support for predicate hierarchies. Jacy, being the forward-thinking early adopter of new technologies that it is, should also provide this new SEM-I. The old one can be discarded (does anyone use it?).

I think there is a lisp function in the LKB for this. See this thread for more information: http://lists.delph-in.net/archives/developers/2016/002293.html

Also, the ERG puts its SEM-I and related files in a subdirectory (`etc/`, though I think something like `sem-i/` would be more descriptive; also I'm not a fan of `patches.lisp` and wouldn't want to encourage using scripts to change the SEM-I so that it no longer accurately describes the grammar).

**Comment by goodmami** [comment]
Is it possible to merge this and create a new release? There have been a lot of changes since the last release that I would like to include in my work.

**Comment by fcbond** [comment]
Please go ahead and merge.
