### ISSUE TITLE
Negation gives bad semantics.

### ISSUE THREAD

**Issue by goodmami** [delph-in/jacy#4]
In the current convention for MRS, everything should get its own unique intrinsic variable (ARG0) except for quantifiers, which share it with the quantifiee. In Jacy, negation with `"_neg_v_rel"` either shares its intrinsic variable with the negated event with suru-type verbs like in 結婚しない, or gets an `i`-type intrinsic variable (I expected an `e`, but I see the ERG does this, too, with things like "un" as in "unused") with regular verb negation (as in 習わない).

I expected to see both the verb and the negation have their own `e` variables, which happens in adverbal constructions (e.g. 早くする). The ERG works this way, as well.

Also, why don't we use `neg_rel` instead of `"_neg_v_rel"`? The predicative 無い (as in 訳が無い) gets treated as `"neg_rel"`, though, which seems backwards to me.

**Comment by goodmami** [comment]
Possibly a duplicate, or at least similar to, #1

**Comment by fcbond** [comment]
Which version of the grammar are you using?

With a fresh clone of github I get correct parses for both 結婚しない and 犬がない.

 (lkb::do-parse-tty "犬 が 結婚 し ない")

Edge number 242
(UTT (VP (PP (N (N (犬))) (CASE-P (が))) (V (V (V (結婚)) (V (V (し)))) (V
(ない)))))

犬 が 結婚 し ない
 [ LTOP: u1
   INDEX: e2 [ e TENSE: PRES MOOD: INDICATIVE PROG: - PERF: - ASPECT:
DEFAULT_ASPECT PASS: - SF: PROP ]
   RELS: <
          [ udef_q_rel<0:1>
            LBL: h3
            ARG0: x4 [ x PERS: 3 ]
            RSTR: h5
            BODY: h6 ]
          [ "_inu_n_rel"<0:1>
            LBL: h7
            ARG0: x4 ]
          [ "_kekkon_s_2_rel"<4:6>
            LBL: h8
            ARG0: e2
            ARG1: x4 ]
          [ "_neg_v_rel"<9:11>
            LBL: h9
            ARG0: i11
            ARG1: h10 ] >
   HCONS: < h5 qeq h7 h10 qeq h8 > ]




(lkb::do-parse-tty "犬 が ない")

Edge number 69
(UTT (VP (PP (N (N (犬))) (CASE-P (が))) (V (V (V (ない))))))

犬 が ない
 [ LTOP: u1
   INDEX: e2 [ e TENSE: PRES MOOD: INDICATIVE PROG: - PERF: - ASPECT:
DEFAULT_ASPECT PASS: - SF: PROP ]
   RELS: <
          [ udef_q_rel<0:1>
            LBL: h3
            ARG0: x4 [ x PERS: 3 ]
            RSTR: h5
            BODY: h6 ]
          [ "_inu_n_rel"<0:1>
            LBL: h7
            ARG0: x4 ]
          [ "neg_rel"<4:6>
            LBL: h8
            ARG0: i10
            ARG1: h9 ]
          [ "_exist_v_rel"<4:6>
            LBL: h11
            ARG0: e2
            ARG1: x4 ] >
   HCONS: < h5 qeq h7 h9 qeq h11 > ]

I am happy to change all the predicates to neg_rel and make the arg0 an
event.

-- 
Francis Bond <http://www3.ntu.edu.sg/home/fcbond/>
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by goodmami** [comment]
I'm using the latest (1748e925d18139495b769125b88f24f12591d4c8). I checked again, and I got what you did when I did 結婚しない but the duplicated ARG0 when I do 結婚しなかった.

RE: the _neg_v_rel/neg_rel and {non-,}eventual ARG0s, I just found them surprising. I'd be happy to defer those decisions to more experienced grammar developers. Would the neg_rel thing fall in with the predicate-hierarchy harmonization efforts?
