### ISSUE TITLE
tmr/punctuation.tdl file appears unused

### ISSUE THREAD

**Issue by goodmami** [delph-in/jacy#42]
While investigating #41 , I noticed that `default_carg_tmr` is defined in both `tmr/punctuation.tdl` and `tmr/prelude.tdl` (almost the same, but `+TNT #tnt` is replaced with `+POS #pos` in `tmr/prelude.tmr`). The `tmr/punctuation.tdl` file doesn't appear to be used by any configs of Jacy (ACE, LKB, or PET).

Also, prelude.tmr doesn't have a mode line at the top, so syntax highlighting doesn't work in emacs.

**Comment by fcbond** [comment]
I added a mode-line to prelude.tmr, I will leave punctuation.tdl there as a source of inspiration.
So fixed in 
7f4a1c4b6386c03409f765fe08680138d810f9f6
